export const MOCK_EVENTS = [
  {
    _id: "1",
    title: "Luxury Family Apartment",
    description: "Spacious apartment with modern facilities.",
    location: "Dhanmondi, Dhaka",
    rent: 28000,
    bedrooms: 3,
    bathrooms: 2,
    area: "1400 sqft",
    propertyType: "Apartment",
    image: "https://images.unsplash.com/photo-1560185008-b033106af5c3",
    ownerName: "Rahim Uddin",
    ownerEmail: "rahim@example.com",
    status: "Available",
  },
  {
    _id: "2",
    title: "Modern Studio Flat",
    description: "Perfect for students and bachelors.",
    location: "Agrabad, Chattogram",
    rent: 12000,
    bedrooms: 1,
    bathrooms: 1,
    area: "550 sqft",
    propertyType: "Studio",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    ownerName: "Karim Hasan",
    ownerEmail: "karim@example.com",
    status: "Available",
  },
  {
    _id: "3",
    title: "Premium Duplex House",
    description: "Luxury duplex with rooftop garden.",
    location: "Uttara, Dhaka",
    rent: 55000,
    bedrooms: 5,
    bathrooms: 4,
    area: "3000 sqft",
    propertyType: "Duplex",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    ownerName: "Nusrat Jahan",
    ownerEmail: "nusrat@example.com",
    status: "Available",
  },
  {
    _id: "4",
    title: "Cozy Family House",
    description: "Comfortable house in a quiet neighborhood.",
    location: "Sylhet",
    rent: 18000,
    bedrooms: 2,
    bathrooms: 2,
    area: "1000 sqft",
    propertyType: "House",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    ownerName: "Arif Hossain",
    ownerEmail: "arif@example.com",
    status: "Booked",
  },
  {
    _id: "5",
    title: "Elegant Penthouse",
    description: "Penthouse with city skyline view.",
    location: "Banani, Dhaka",
    rent: 80000,
    bedrooms: 4,
    bathrooms: 4,
    area: "3500 sqft",
    propertyType: "Penthouse",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    ownerName: "Sabbir Ahmed",
    ownerEmail: "sabbir@example.com",
    status: "Available",
  },
  {
    _id: "6",
    title: "Affordable Bachelor Room",
    description: "Budget-friendly room for bachelors.",
    location: "Mirpur, Dhaka",
    rent: 7000,
    bedrooms: 1,
    bathrooms: 1,
    area: "350 sqft",
    propertyType: "Room",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    ownerName: "Tanvir Islam",
    ownerEmail: "tanvir@example.com",
    status: "Available",
  },
  {
    _id: "7",
    title: "Lake View Apartment",
    description: "Apartment with a beautiful lake view.",
    location: "Khulna",
    rent: 24000,
    bedrooms: 3,
    bathrooms: 2,
    area: "1350 sqft",
    propertyType: "Apartment",
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858",
    ownerName: "Mehedi Hasan",
    ownerEmail: "mehedi@example.com",
    status: "Available",
  },
  {
    _id: "8",
    title: "Minimalist Condo",
    description: "Modern condo with premium amenities.",
    location: "Rajshahi",
    rent: 26000,
    bedrooms: 2,
    bathrooms: 2,
    area: "1100 sqft",
    propertyType: "Condo",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde",
    ownerName: "Jannatul Ferdous",
    ownerEmail: "jannat@example.com",
    status: "Booked",
  },
  {
    _id: "9",
    title: "Luxury Villa",
    description: "Private villa with swimming pool.",
    location: "Cox's Bazar",
    rent: 120000,
    bedrooms: 6,
    bathrooms: 5,
    area: "5000 sqft",
    propertyType: "Villa",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227",
    ownerName: "Hasan Mahmud",
    ownerEmail: "hasan@example.com",
    status: "Available",
  },
  {
    _id: "10",
    title: "Smart City Apartment",
    description: "Fully furnished smart apartment.",
    location: "Cumilla",
    rent: 32000,
    bedrooms: 3,
    bathrooms: 2,
    area: "1500 sqft",
    propertyType: "Apartment",
    image: "https://images.unsplash.com/photo-1605146769289-440113cc3d00",
    ownerName: "Fahim Ahmed",
    ownerEmail: "fahim@example.com",
    status: "Available",
  },
];